# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibexp" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "a7317fe9f6b5f530636b79560850ffed80f6e801a586e930be9831b09334ed31"
      url "https://github.com/vibexp/cli/releases/download/v#{version}/vibexp_homebrew_#{version}_darwin-amd64.tar.gz",
        verified: "github.com/vibexp/cli/"
    end
    on_arm do
      sha256 "24a08fa2b1c4f4adfdc18a51c978a5dfaea67f79773d8d2494bc551be27eef84"
      url "https://github.com/vibexp/cli/releases/download/v#{version}/vibexp_homebrew_#{version}_darwin-arm64.tar.gz",
        verified: "github.com/vibexp/cli/"
    end
  end

  name "vibexp"
  desc "Command-line interface for the VibeXP platform"
  homepage "https://github.com/vibexp/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibexp"
  manpage "manpages/vibexp.1"
  bash_completion "completions/vibexp.bash"
  fish_completion "completions/vibexp.fish"
  zsh_completion "completions/vibexp.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/vibexp"]
    end
  end

  # No zap stanza required

end
