# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibexp" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "b81c1c450e1c9e067bb0e097ea142864247b689bfceafb5d087f32a44a93f978"
      url "https://github.com/vibexp/cli/releases/download/v#{version}/vibexp_homebrew_#{version}_darwin-amd64.tar.gz",
        verified: "github.com/vibexp/cli/"
    end
    on_arm do
      sha256 "aac3ec02fda27a7f5b03427433b10f10507e674e33f2822e390f1614e3d420a5"
      url "https://github.com/vibexp/cli/releases/download/v#{version}/vibexp_homebrew_#{version}_darwin-arm64.tar.gz",
        verified: "github.com/vibexp/cli/"
    end
  end

  name "vibexp"
  desc "Command-line interface for the VibeXP platform"
  homepage "https://github.com/vibexp/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibexp"
  manpage "manpages/vibexp.1"
  bash_completion "completions/vibexp.bash"
  fish_completion "completions/vibexp.fish"
  zsh_completion "completions/vibexp.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/vibexp"]
    end
  end

  # No zap stanza required

end
