# This file was generated by GoReleaser. DO NOT EDIT.
cask "vibexp" do
  version "0.4.0"

  on_macos do
    on_intel do
      sha256 "35a0dcc98625f832bfcdb60ff8381b6d236d5c27ca110ea7a62f198dc48e197f"
      url "https://github.com/vibexp/cli/releases/download/v#{version}/vibexp_homebrew_#{version}_darwin-amd64.tar.gz",
        verified: "github.com/vibexp/cli/"
    end
    on_arm do
      sha256 "def0476ecc0154d04c76a9acebbc5a5780564d256661add5e56f9c08eb4a59b9"
      url "https://github.com/vibexp/cli/releases/download/v#{version}/vibexp_homebrew_#{version}_darwin-arm64.tar.gz",
        verified: "github.com/vibexp/cli/"
    end
  end

  name "vibexp"
  desc "Command-line interface for the VibeXP platform"
  homepage "https://github.com/vibexp/cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vibexp"
  manpage "manpages/vibexp.1"
  bash_completion "completions/vibexp.bash"
  fish_completion "completions/vibexp.fish"
  zsh_completion "completions/vibexp.zsh"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/vibexp"]
    end
  end

  # No zap stanza required

end
